version: '3.7'

services:
  mongo:
    image: mongo:4.2.23-bionic
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  app:
    build: .
    port:
     - 8080:8080 